secret_key_base: m_Md8xqtPcSj_XYkyged7B7j0IxcvFdIOqV9vp--0bY
port: 3000
name: movie_app0

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://movieApp1129034120:12345@localhost:5432/movie_app0_development
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
