 header.header.header-inverse.h-fullscreen.p-0.bg-primary.overflow-hidden.orange-header
.row.justify-content-center
  .col-sm-12.col-md-6
    center
    h1 = "Bienvenido"
    p Aqui podras encontrar todas tus peliculas favoritas y armar una lista de las que mas te gustan.
    p Busca por el nombre y agregalas a tus favoritos.
    .container
    center
        br
        a.btn.btn-lg.btn-round.shadow-3.btn-primary href="http://localhost:3000/movies" Buscar Pelicula